#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/devmysql
#    username: root
#    password: password
#    driver-class-name: com.mysql.jdbc.Driver
#    schema: classpath:ssschema.sql
#  jpa:
#    hibernate:
#        ddl-auto: create-drop
#    test-on-borrow: true
#    validate-query: /* ping  */
